spring.datasource.url=jdbc:postgresql://db:5432/${POSTGRESQL_DATABASE}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}
supabase.bucket-photos=${SUPABASE_BUCKET_NAME}
supabase.bucket-signatures=${SUPABASE_BUCKET_NAME}